//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public string nosession { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public string prix { get; set; }
        public string paticipant_id { get; set; }
        public string animateur_id { get; set; }
        public string nocours { get; set; }
    
        public virtual Animateur Animateur { get; set; }
        public virtual Cour Cour { get; set; }
        public virtual Parrticipant Parrticipant { get; set; }
    }
}
